server:
  port: 8088

spring:
  application:
    name: eureka-zuul

zuul:
  prefix: /api
  # 声明路由
  routes:
    xxx-server: /manage/**
    search-server: /search/**
    user-server: /user-center/**
    oauth-server: /oauth/**
    car-server: /car/**
    order-server: /order/**
    pay-server: /pay/**
    recommend-server: /recommend/**
#    api-search:
#      path: /api-search/**
#      serviceId: search-server
    # 路由名称
#    api-xxx:
#      # 声明将所有以/api-xxx/的请求都转发到xxx-service的服务中
#      path: /api-xxx/**
#      serviceId: xxx-server
  # 启用重试
  retryable: true

  # 包含此路径的不进行路由
  #ignored-patterns: /upload/**
  # 忽略上传服务
  #ignored-services:
   # -upload-server
  sensitive-headers:
  add-host-header: true


#配置负载
ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000 # 熔断超时时长：6000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mrshop:
  #声明不进行拦截的请求用,分隔
  filter:
    excludes: /api/oauth/oauth/login,/api/user-center/user/register,/api/oauth/oauth/verify,/api/search/es/search,/api/recommend/recommend/getGoodsInfo,/api/pay/pay/UnionpayPay
  jwt:
    pubkeyPath: G:\secret\rea.pub # 公钥地址(私钥加密,公钥解密)
    cookieName: MRSHOP_TOKEN