server:
  port: 8300

spring:
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200
  application:
    name: search-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#日志设置
logging:
  level:
    # 打印与我们程序相关的日志信息
    com.baidu.shop: debug



