server:
  port: 8300

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # 是否确认回调
    publisher-confirm-type: correlated
    # 是否返回回调
    publisher-returns: true
    virtual-host: /
    # 手动确认
    listener:
      simple:
        acknowledge-mode: manual
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200
  application:
    name: search-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#日志设置
logging:
  level:
    # 打印与我们程序相关的日志信息
    com.baidu.shop: debug



